[package]
name = "kunzite"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# print opcode info when decoding
debug_opcode = []

[dependencies]
gui = { path = "../gui" }

color-eyre = "0.5.11"